site_name: Documentação - Malha Fundiária Ambiental
site_author: Bernard Silva de Oliveira
theme: 'readthedocs'
 
nav:
  - 'Home': 'index.md'
  - 'Ingestão de Dados':'1-Ingestão de Dados.md'
  - 'Pré-processamento': '2-Pré processamento dos dados.md'
  - 'Conversão de estrutura Matricial': '3-Conversão de estrutura Matricial.md'
  - 'Hierarquização': '4-Hierarquização.md'
  - 'Integração Fundiária e Ambiental': 'docs/5-Integração Fundiária e Ambiental.md' 
